import { useEffect, useState } from 'react';
import { Assignment, Entry, Team, Timesheet, User, Worker, workforceApi } from './api/workforce';
import { apiError, authApi } from './api/client';

const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><div className={`card ${className}`}>{children}</div>;
const Empty=({text}:{text:string})=><div className="py-14 text-center text-slate-400">{text}</div>;
const ErrorText=({text}:{text:string})=>text?<p className="text-sm text-red-600 bg-red-50 p-3 rounded-xl mb-4">{text}</p>:null;
const err=(e:any)=>apiError(e);

export function DashboardView({user}:{user:User}){
  const [data,setData]=useState<Record<string,any>>({});
  useEffect(()=>{workforceApi.dashboard().then(setData)},[]);
  return <><div className="grid grid-cols-1 md:grid-cols-3 gap-5">{Object.entries(data).filter(([k])=>k!=='role').map(([key,value],i)=><Card key={key} className={`metric-card metric-${i%3}`}><div className="metric-orb"/><p className="relative text-xs font-bold text-slate-500 uppercase tracking-wider">{key.replace(/_/g,' ')}</p><p className="relative text-4xl font-extrabold text-slate-900 mt-4 tracking-tight">{value}</p><div className="relative mt-4 h-1.5 bg-slate-100 rounded-full overflow-hidden"><div className="h-full w-2/3 rounded-full bg-current"/></div></Card>)}</div><Card className="mt-6 bg-gradient-to-br from-white to-blue-50/60"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 shadow-lg shadow-blue-500/20 grid place-items-center text-white font-extrabold text-xl">{user.name.charAt(0)}</div><div><h2 className="section-title">Welcome back, {user.name}</h2><p className="text-slate-500 mt-1">{user.role==='admin'?'Organization-wide visibility across workers, managers, teams, assignments and timesheets.':user.role==='hr'?'Onboard and manage the complete worker lifecycle.':user.role==='manager'?'Manage assignments and track hours for your authorized teams.':'Review assignments and keep your weekly hours up to date.'}</p></div></div></Card></>
}

export function TeamsView({user}:{user:User}){
  const [teams,setTeams]=useState<Team[]>([]); const [managers,setManagers]=useState<User[]>([]); const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',description:'',manager_id:''});
  const load=()=>workforceApi.teams().then(setTeams).catch(e=>setError(err(e)));
  // Only an admin may create a team, so only an admin needs the manager picker.
  useEffect(()=>{load();if(user.role==='admin')authApi.listUsers('MANAGER').then((x:User[])=>setManagers(x))},[]);
  async function create(e:React.FormEvent){e.preventDefault();setError('');try{await workforceApi.createTeam({...form,manager_id:Number(form.manager_id)});setForm({name:'',description:'',manager_id:''});load()}catch(e){setError(err(e))}}
  return <div className="grid lg:grid-cols-[1fr_360px] gap-6"><Card><h2 className="section-title">{user.role==='manager'?'My teams':'All teams'}</h2><div className="mt-5 space-y-3">{teams.length?teams.map(t=><div key={t.id} className="border border-slate-200 rounded-2xl p-5 flex justify-between"><div><h3 className="font-semibold">{t.name}</h3><p className="text-sm text-slate-500 mt-1">{t.description||'No description'}</p></div><span className="pill">{t.manager_name}</span></div>):<Empty text="No teams available"/>}</div></Card>{user.role==='admin'&&<Card><h2 className="section-title">Create team</h2><form onSubmit={create} className="mt-5 space-y-4"><ErrorText text={error}/><input className="input" placeholder="Team name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><textarea className="input" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className="input" value={form.manager_id} onChange={e=>setForm({...form,manager_id:e.target.value})} required><option value="">Select manager</option>{managers.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button className="btn-primary w-full">Create team</button></form></Card>}</div>
}

export function WorkersView({user}:{user:User}){
  const [workers,setWorkers]=useState<Worker[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [error,setError]=useState('');
  const initial={name:'',email:'',employee_code:'',worker_type:'CONTRACTOR',employment_start_date:'',team_id:'',password:''};const [form,setForm]=useState(initial);
  const load=()=>Promise.all([workforceApi.workers(),workforceApi.teams()]).then(([w,t])=>{setWorkers(w);setTeams(t)}).catch(e=>setError(err(e)));
  useEffect(()=>{load()},[]);
  async function onboard(e:React.FormEvent){e.preventDefault();setError('');try{await workforceApi.onboard({...form,team_id:Number(form.team_id)});setForm(initial);load()}catch(e){setError(err(e))}}
  async function offboard(id:number){if(!confirm('Offboard this worker? Historical records will remain.'))return;try{await workforceApi.offboard(id);load()}catch(e){setError(err(e))}}
  return <div className={`grid ${user.role==='hr'?'xl:grid-cols-[1fr_380px]':'grid-cols-1'} gap-6`}><Card><h2 className="section-title">Worker directory</h2><ErrorText text={error}/><div className="overflow-x-auto mt-5"><table><thead><tr><th>Worker</th><th>Code</th><th>Type</th><th>Team</th><th>Status</th>{user.role==='hr'&&<th/>}</tr></thead><tbody>{workers.map(w=><tr key={w.id}><td><b>{w.name}</b><small>{w.email}</small></td><td>{w.employee_code}</td><td>{w.worker_type}</td><td>{w.team_name}</td><td><span className={w.status==='ACTIVE'?'status-green':'status-gray'}>{w.status}</span></td>{user.role==='hr'&&<td>{w.status==='ACTIVE'&&<button onClick={()=>offboard(w.id)} className="text-red-600 text-sm font-semibold">Offboard</button>}</td>}</tr>)}</tbody></table>{!workers.length&&<Empty text="No workers available"/>}</div></Card>{user.role==='hr'&&<Card><h2 className="section-title">Onboard worker</h2><form onSubmit={onboard} className="mt-5 space-y-3"><input className="input" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="input" type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input className="input" placeholder="Employee code" value={form.employee_code} onChange={e=>setForm({...form,employee_code:e.target.value})} required/><select className="input" value={form.worker_type} onChange={e=>setForm({...form,worker_type:e.target.value})}><option>CONTRACTOR</option><option>EMPLOYEE</option><option>TEMPORARY_WORKER</option></select><input className="input" type="date" value={form.employment_start_date} onChange={e=>setForm({...form,employment_start_date:e.target.value})} required/><select className="input" value={form.team_id} onChange={e=>setForm({...form,team_id:e.target.value})} required><option value="">Select team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input className="input" type="password" minLength={8} placeholder="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button className="btn-primary w-full">Onboard worker</button></form></Card>}</div>
}

export function AssignmentsView({user}:{user:User}){
  const [items,setItems]=useState<Assignment[]>([]);const [workers,setWorkers]=useState<Worker[]>([]);const [error,setError]=useState('');
  const initial={worker_id:'',title:'',description:'',start_date:'',end_date:''};const [form,setForm]=useState(initial);
  const load=()=>workforceApi.assignments().then(setItems).catch(e=>setError(err(e)));
  useEffect(()=>{load();if(user.role==='manager')workforceApi.workers({status:'ACTIVE'}).then(setWorkers)},[]);
  async function create(e:React.FormEvent){e.preventDefault();setError('');try{await workforceApi.createAssignment({...form,worker_id:Number(form.worker_id)});setForm(initial);load()}catch(e){setError(err(e))}}
  return <div className={`grid ${user.role==='manager'?'xl:grid-cols-[1fr_380px]':'grid-cols-1'} gap-6`}><Card><h2 className="section-title">{user.role==='worker'?'My assignments':user.role==='manager'?'Team assignments':'All assignments'}</h2><ErrorText text={error}/><div className="grid md:grid-cols-2 gap-4 mt-5">{items.map(a=><div key={a.id} className="border border-slate-200 rounded-2xl p-5"><div className="flex justify-between gap-3"><h3 className="font-semibold text-lg">{a.title}</h3><span className="status-green">{a.status}</span></div><p className="text-sm text-slate-500 mt-2 min-h-10">{a.description||'No description'}</p><div className="mt-4 pt-4 border-t text-sm grid grid-cols-2 gap-2"><span className="text-slate-500">Worker</span><b className="text-right">{a.worker_name}</b><span className="text-slate-500">Team</span><b className="text-right">{a.team_name}</b><span className="text-slate-500">Manager</span><b className="text-right">{a.manager_name}</b><span className="text-slate-500">Dates</span><b className="text-right text-xs">{a.start_date} → {a.end_date}</b></div></div>)}{!items.length&&<Empty text="No assignments available"/>}</div></Card>{user.role==='manager'&&<Card><h2 className="section-title">Create assignment</h2><form onSubmit={create} className="mt-5 space-y-3"><select className="input" value={form.worker_id} onChange={e=>setForm({...form,worker_id:e.target.value})} required><option value="">Select active worker</option>{workers.map(w=><option key={w.id} value={w.id}>{w.name} · {w.team_name}</option>)}</select><input className="input" placeholder="Assignment title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><textarea className="input" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="label">Start date</label><input className="input" type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})} required/><label className="label">End date <span className="text-slate-400 font-normal">(optional)</span></label><input className="input" type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/><button className="btn-primary w-full">Create assignment</button></form></Card>}</div>
}

const iso=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const monday=()=>{const d=new Date();const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return iso(d)};
const weekEntries=(start:string):Entry[]=>{if(!start)return[];const base=new Date(start+'T00:00:00');return Array.from({length:7},(_,i)=>{const d=new Date(base);d.setDate(base.getDate()+i);return{work_date:iso(d),hours:0}})};

export function TimesheetsView({user}:{user:User}){
  const [sheets,setSheets]=useState<Timesheet[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [error,setError]=useState('');
  const [assignmentId,setAssignmentId]=useState('');const [weekStart,setWeekStart]=useState(monday());const [entries,setEntries]=useState<Entry[]>(weekEntries(monday()));
  const load=()=>workforceApi.timesheets().then(setSheets).catch(e=>setError(err(e)));
  useEffect(()=>{load();if(user.role==='worker')workforceApi.assignments().then(setAssignments)},[]);
  const total=entries.reduce((sum,x)=>sum+Number(x.hours),0);
  async function save(e:React.FormEvent){e.preventDefault();setError('');try{await workforceApi.createTimesheet({assignment_id:Number(assignmentId),week_start:weekStart,entries});setAssignmentId('');load()}catch(e){setError(err(e))}}
  async function saveDraft(sheet:Timesheet){try{await workforceApi.updateTimesheet(sheet.id,sheet.entries);load()}catch(e){setError(err(e))}}
  function editDraft(sheetId:number,index:number,hours:number){setSheets(sheets.map(sheet=>sheet.id===sheetId?{...sheet,entries:sheet.entries.map((entry,i)=>i===index?{...entry,hours}:entry),total_hours:sheet.entries.reduce((sum,entry,i)=>sum+(i===index?hours:Number(entry.hours)),0)}:sheet))}
  async function submit(id:number){if(!confirm('Submit this timesheet? It will become read-only.'))return;try{await workforceApi.submitTimesheet(id);load()}catch(e){setError(err(e))}}
  return <div className={`grid ${user.role==='worker'?'xl:grid-cols-[1fr_400px]':'grid-cols-1'} gap-6`}><Card><h2 className="section-title">{user.role==='worker'?'My weekly timesheets':user.role==='manager'?'Team timesheets':'Organization timesheets'}</h2><p className="text-sm text-slate-500 mt-1">Managers view and track hours. There is no approval workflow.</p><ErrorText text={error}/><div className="space-y-4 mt-5">{sheets.map(s=><div key={s.id} className="border border-slate-200 rounded-2xl p-5"><div className="flex items-start justify-between"><div><h3 className="font-semibold">{s.worker_name} · {s.assignment_title}</h3><p className="text-sm text-slate-500 mt-1">{s.week_start} → {s.week_end}</p></div><span className={s.status==='SUBMITTED'?'status-blue':'status-gray'}>{s.status}</span></div><div className="grid grid-cols-7 gap-2 mt-5">{s.entries.map((x,i)=><div key={x.work_date} className="bg-slate-50 rounded-xl p-2 text-center"><div className="text-[10px] text-slate-400 uppercase">{new Date(x.work_date+'T00:00:00').toLocaleDateString('en',{weekday:'short'})}</div>{user.role==='worker'&&s.status==='DRAFT'?<input className="w-full mt-1 text-center border rounded py-1 font-bold" type="number" min="0" max="24" step="0.5" value={x.hours} onChange={e=>editDraft(s.id,i,Number(e.target.value))}/>:<div className="font-bold mt-1">{x.hours}</div>}</div>)}</div><div className="mt-4 flex justify-between items-center"><b>Total: {s.total_hours} hours</b>{user.role==='worker'&&s.status==='DRAFT'&&<div className="flex gap-2"><button onClick={()=>saveDraft(s)} className="pill">Save changes</button><button onClick={()=>submit(s.id)} className="btn-primary">Submit</button></div>}</div></div>)}{!sheets.length&&<Empty text="No timesheets available"/>}</div></Card>
  {user.role==='worker'&&<Card><h2 className="section-title">Create weekly timesheet</h2><form onSubmit={save} className="mt-5 space-y-3"><select className="input" value={assignmentId} onChange={e=>setAssignmentId(e.target.value)} required><option value="">Select assignment</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><label className="label">Week starting Monday</label><input className="input" type="date" value={weekStart} onChange={e=>{setWeekStart(e.target.value);setEntries(weekEntries(e.target.value))}} required/><div className="space-y-2">{entries.map((x,i)=><label key={x.work_date} className="flex items-center justify-between text-sm"><span>{new Date(x.work_date+'T00:00:00').toLocaleDateString('en',{weekday:'long'})}</span><input className="w-24 border rounded-lg px-3 py-2" type="number" min="0" max="24" step="0.5" value={x.hours} onChange={e=>setEntries(entries.map((v,j)=>j===i?{...v,hours:Number(e.target.value)}:v))}/></label>)}</div><div className="flex justify-between font-bold pt-3 border-t"><span>Total</span><span>{total} hours</span></div><button className="btn-primary w-full">Save draft</button></form></Card>}</div>
}
